## Titanic Survived Prediction using Decision Tree

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import mean_squared_error, r2_score
import warnings
warnings.filterwarnings("ignore")
from sklearn.preprocessing import StandardScaler


Data Loading , Feature Selection and Preprocessing

In [5]:
data= pd.read_csv('/content/drive/MyDrive/Titanic-Dataset.csv')
data

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0              1         0       3  ...   7.2500   NaN         S
1              2         1       1  ...  71.2833   C85         C
2              3         1       3  ...   7.9250   NaN         S
3              4         1       1  ...  53.1000  C123         S
4              5         0       3  ...   8.0500   NaN         S
..           ...       ...     ...  ...      ...   ...       ...
886          887         0       2  ...  13.0000   NaN         S
887          888         1       1  ...  30.0000   B42         S
888          889         0       3  ...  23.4500   NaN         S
889          890         1       1  ...  30.0000  C148         C
890          891         0       3  ...   7.7500   NaN         Q

[891 rows x 12 columns]

In [9]:
data.dropna(inplace=True)


In [11]:

mapping= { 'C':0,'S':1,'Q':2}
data['Embarked']= data['Embarked'].map(mapping)
data

PassengerId  Survived  Pclass  ...     Fare        Cabin  Embarked
1              2         1       1  ...  71.2833          C85         0
3              4         1       1  ...  53.1000         C123         1
6              7         0       1  ...  51.8625          E46         1
10            11         1       3  ...  16.7000           G6         1
11            12         1       1  ...  26.5500         C103         1
..           ...       ...     ...  ...      ...          ...       ...
871          872         1       1  ...  52.5542          D35         1
872          873         0       1  ...   5.0000  B51 B53 B55         1
879          880         1       1  ...  83.1583          C50         0
887          888         1       1  ...  30.0000          B42         1
889          890         1       1  ...  30.0000         C148         0

[183 rows x 12 columns]

In [13]:
data= data.join(pd.get_dummies(data['Sex']).astype(int)).drop('Sex',axis=1)
data

PassengerId  Survived  Pclass  ... Embarked  female  male
1              2         1       1  ...        0       1     0
3              4         1       1  ...        1       1     0
6              7         0       1  ...        1       0     1
10            11         1       3  ...        1       1     0
11            12         1       1  ...        1       1     0
..           ...       ...     ...  ...      ...     ...   ...
871          872         1       1  ...        1       1     0
872          873         0       1  ...        1       0     1
879          880         1       1  ...        0       1     0
887          888         1       1  ...        1       1     0
889          890         1       1  ...        0       0     1

[183 rows x 13 columns]

In [20]:
data.drop('male',axis=1,inplace=True)
data

data

PassengerId  Survived  Pclass  ...        Cabin  Embarked  female
1              2         1       1  ...          C85         0       1
3              4         1       1  ...         C123         1       1
6              7         0       1  ...          E46         1       0
10            11         1       3  ...           G6         1       1
11            12         1       1  ...         C103         1       1
..           ...       ...     ...  ...          ...       ...     ...
871          872         1       1  ...          D35         1       1
872          873         0       1  ...  B51 B53 B55         1       0
879          880         1       1  ...          C50         0       1
887          888         1       1  ...          B42         1       1
889          890         1       1  ...         C148         0       0

[183 rows x 12 columns]

In [23]:
#dropping the name
data.drop('Name',axis=1,inplace =True)
data


Survived  Pclass   Age  SibSp  Parch    Ticket     Fare        Cabin  Embarked  female
1           1       1  38.0      1      0  PC 17599  71.2833          C85         0       1
3           1       1  35.0      1      0    113803  53.1000         C123         1       1
6           0       1  54.0      0      0     17463  51.8625          E46         1       0
10          1       3   4.0      1      1   PP 9549  16.7000           G6         1       1
11          1       1  58.0      0      0    113783  26.5500         C103         1       1
..        ...     ...   ...    ...    ...       ...      ...          ...       ...     ...
871         1       1  47.0      1      1     11751  52.5542          D35         1       1
872         0       1  33.0      0      0       695   5.0000  B51 B53 B55         1       0
879         1       1  56.0      0      1     11767  83.1583          C50         0       1
887         1       1  19.0      0      0    112053  30.0000          B42         1       1
889         1       1  26.0      0      0    111369  30.0000         C148         0       0

[183 rows x 10 columns]

In [25]:
data=data.join(pd.get_dummies(data['Cabin']).astype(int)).drop('Cabin',axis=1)
data

Survived  Pclass   Age  SibSp  Parch    Ticket     Fare  ...  F G63  F G73  F2  F33  F4  G6  T
1           1       1  38.0      1      0  PC 17599  71.2833  ...      0      0   0    0   0   0  0
3           1       1  35.0      1      0    113803  53.1000  ...      0      0   0    0   0   0  0
6           0       1  54.0      0      0     17463  51.8625  ...      0      0   0    0   0   0  0
10          1       3   4.0      1      1   PP 9549  16.7000  ...      0      0   0    0   0   1  0
11          1       1  58.0      0      0    113783  26.5500  ...      0      0   0    0   0   0  0
..        ...     ...   ...    ...    ...       ...      ...  ...    ...    ...  ..  ...  ..  .. ..
871         1       1  47.0      1      1     11751  52.5542  ...      0      0   0    0   0   0  0
872         0       1  33.0      0      0       695   5.0000  ...      0      0   0    0   0   0  0
879         1       1  56.0      0      1     11767  83.1583  ...      0      0   0    0   0   0  0
887         1       1  19.0      0      0    112053  30.0000  ...      0      0   0    0   0   0  0
889         1       1  26.0      0      0    111369  30.0000  ...      0      0   0    0   0   0  0

[183 rows x 142 columns]

In [26]:
data=data.join(pd.get_dummies(data['Ticket']).astype(int)).drop('Ticket',axis=1)
data

Survived  Pclass   Age  SibSp  ...  SC/Paris 2163  SOTON/O.Q. 392078  W.E.P. 5734  WE/P 5735
1           1       1  38.0      1  ...              0                  0            0          0
3           1       1  35.0      1  ...              0                  0            0          0
6           0       1  54.0      0  ...              0                  0            0          0
10          1       3   4.0      1  ...              0                  0            0          0
11          1       1  58.0      0  ...              0                  0            0          0
..        ...     ...   ...    ...  ...            ...                ...          ...        ...
871         1       1  47.0      1  ...              0                  0            0          0
872         0       1  33.0      0  ...              0                  0            0          0
879         1       1  56.0      0  ...              0                  0            0          0
887         1       1  19.0      0  ...              0                  0            0          0
889         1       1  26.0      0  ...              0                  0            0          0

[183 rows x 268 columns]

In [33]:
data.corr()['Survived']

Survived             1.000000
Pclass              -0.034542
Age                 -0.254085
SibSp                0.106346
Parch                0.023582
                       ...   
SC/AH Basle 541      0.051771
SC/Paris 2163       -0.106131
SOTON/O.Q. 392078    0.051771
W.E.P. 5734         -0.106131
WE/P 5735           -0.038544
Name: Survived, Length: 268, dtype: float64

Training using Decision Tree Classifier.

In [34]:
#Splitting The data
x_train,x_test,y_train,y_test= train_test_split(data.drop('Survived',axis=1),data['Survived'],test_size=0.3,random_state=42)

In [35]:
#Scalling the Data
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [36]:
#Decision Tree Model training
model_decision =DecisionTreeClassifier()
model_decision.fit(x_train,y_train)

DecisionTreeClassifier()

In [37]:
#Accuracy Score
from sklearn.metrics import accuracy_score
prediction=model_decision.predict(x_test)
accuracy_score(y_test,prediction)

0.7272727272727273

In [38]:
#Consufion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,prediction)

array([[15,  5],
       [10, 25]])

In [39]:
#auc and roc
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,prediction)

0.7321428571428572

In [40]:
#f1
from sklearn.metrics import f1_score
f1_score(y_test,prediction)

0.7692307692307693

In [41]:
#recall
from sklearn.metrics import recall_score
recall_score(y_test,prediction)

0.7142857142857143

## Titanic Using Regression Model and Naive Bias Classifier

In [42]:
x_train,x_test,y_train,y_test= train_test_split(data.drop('Survived',axis=1),data['Survived'],test_size=0.3,random_state=42)


In [43]:
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [44]:
#Using GaussianNb for Naive Bias Classification for the same data
from sklearn.naive_bayes import GaussianNB
model_naive=GaussianNB()
model_naive.fit(x_train,y_train)

GaussianNB()

In [50]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
predict_naive=model_naive.predict(x_test)
accuracy_score(y_test,predict_naive)
print(classification_report(y_test,predict_naive))
print(confusion_matrix(y_test,predict_naive))

              precision    recall  f1-score   support

           0       0.43      0.80      0.56        20
           1       0.78      0.40      0.53        35

    accuracy                           0.55        55
   macro avg       0.61      0.60      0.54        55
weighted avg       0.65      0.55      0.54        55

[[16  4]
 [21 14]]


In [52]:
from sklearn.metrics import accuracy_score
predict_naive=model_naive.predict(x_test)
accuracy_score(y_test,predict_naive)

0.5454545454545454

## Using Logistic

In [56]:
from sklearn.linear_model import LogisticRegression
model_logistic=LogisticRegression()
model_logistic.fit(x_train,y_train)



LogisticRegression()

In [57]:
from sklearn.metrics import accuracy_score
y_pred_logistic=model_logistic.predict(x_test)
accuracy_score(y_test,y_pred_logistic)

0.7454545454545455

In [58]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(classification_report(y_test,y_pred_logistic))
print(confusion_matrix(y_test,y_pred_logistic))

              precision    recall  f1-score   support

           0       0.67      0.60      0.63        20
           1       0.78      0.83      0.81        35

    accuracy                           0.75        55
   macro avg       0.73      0.71      0.72        55
weighted avg       0.74      0.75      0.74        55

[[12  8]
 [ 6 29]]
